### PR TITLE
Support new heading syntax

### LINKED ISSUE #1: Use new markup

### PR DESCRIPTION
**Pull request by kemitchell**
@anseljh, I'm not set up for Atom testing at the moment. Any chance you
might drop this in --- or just make the edit to your local copy --- and
see what happens?

### CODE REVIEW

**Comment by kemitchell** [comment]
The Atom package manager build failed. Oh, joy.

**Comment by anseljh** [comment]
I plugged this into my local config. No dice.

**Comment by kemitchell** [comment]
Amended. Working in my new local Atom.

**Comment by anseljh** [comment]
:+1:

**Comment by kemitchell** [comment]
Published as new 0.2.0.

**Comment by anseljh** [comment]
Magic!
2015-12-02-atom-update

**Pull request merged**
